# Generated by Django 5.2.2 on 2025-06-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_flights', models.PositiveIntegerField(default=0)),
                ('departed_flights', models.PositiveIntegerField(default=0)),
                ('delayed_flights', models.PositiveIntegerField(default=0)),
                ('cancelled_flights', models.PositiveIntegerField(default=0)),
                ('total_passengers', models.PositiveIntegerField(default=0)),
                ('checked_in_passengers', models.PositiveIntegerField(default=0)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('confirmed_bookings', models.PositiveIntegerField(default=0)),
                ('cancelled_bookings', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('economy_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('business_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('first_class_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active_gates', models.PositiveIntegerField(default=0)),
                ('occupied_gates', models.PositiveIntegerField(default=0)),
                ('maintenance_gates', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='QuickAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(help_text='CSS class for icon', max_length=50)),
                ('url_name', models.CharField(help_text='Django URL name', max_length=100)),
                ('color', models.CharField(default='primary', help_text='Bootstrap color class', max_length=20)),
                ('available_for_admin', models.BooleanField(default=False)),
                ('available_for_staff', models.BooleanField(default=False)),
                ('available_for_airline_staff', models.BooleanField(default=False)),
                ('available_for_passenger', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('category', models.CharField(choices=[('system', 'System'), ('security', 'Security'), ('maintenance', 'Maintenance'), ('performance', 'Performance'), ('booking', 'Booking'), ('flight', 'Flight')], default='system', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('auto_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('booking_created', 'Booking Created'), ('booking_cancelled', 'Booking Cancelled'), ('check_in', 'Check-in Completed'), ('boarding_pass_generated', 'Boarding Pass Generated'), ('flight_created', 'Flight Created'), ('flight_updated', 'Flight Updated'), ('flight_cancelled', 'Flight Cancelled'), ('announcement_created', 'Announcement Created'), ('user_registered', 'User Registered'), ('profile_updated', 'Profile Updated'), ('password_changed', 'Password Changed')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
