# Generated by Django 5.2.2 on 2025-06-07 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baggage_tag', models.CharField(editable=False, max_length=20, unique=True)),
                ('baggage_type', models.CharField(choices=[('carry_on', 'Carry On'), ('checked', 'Checked'), ('special', 'Special')], default='checked', max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('checked_in', 'Checked In'), ('in_transit', 'In Transit'), ('loaded', 'Loaded on Aircraft'), ('in_flight', 'In Flight'), ('arrived', 'Arrived'), ('delivered', 'Delivered'), ('lost', 'Lost'), ('damaged', 'Damaged')], default='checked_in', max_length=20)),
                ('last_location', models.CharField(blank=True, max_length=100)),
                ('special_handling', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardingPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_pass_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='boarding_passes/')),
                ('gate_number', models.CharField(blank=True, max_length=10)),
                ('boarding_time', models.DateTimeField()),
                ('seat_number', models.CharField(max_length=5)),
                ('sequence_number', models.PositiveIntegerField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pilot', 'Pilot'), ('co_pilot', 'Co-Pilot'), ('flight_attendant', 'Flight Attendant'), ('ground_crew', 'Ground Crew'), ('check_in_staff', 'Check-in Staff'), ('security', 'Security'), ('maintenance', 'Maintenance')], max_length=20)),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['shift_start'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('seat_class', models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First Class')], default='economy', max_length=10)),
                ('seat_type', models.CharField(choices=[('window', 'Window'), ('middle', 'Middle'), ('aisle', 'Aisle')], default='middle', max_length=10)),
                ('row_number', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('extra_legroom', models.BooleanField(default=False)),
                ('exit_row', models.BooleanField(default=False)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['aircraft', 'row_number', 'seat_number'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(editable=False, max_length=10, unique=True)),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_email', models.EmailField(max_length=254)),
                ('passenger_phone', models.CharField(max_length=15)),
                ('passport_number', models.CharField(blank=True, max_length=20)),
                ('seat_class', models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First Class')], default='economy', max_length=10)),
                ('seat_number', models.CharField(blank=True, max_length=5)),
                ('number_of_passengers', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('is_checked_in', models.BooleanField(default=False)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('boarding_pass_issued', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flights.flight')),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
    ]
