# Generated by Django 5.2.2 on 2025-06-07 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('flights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardingpass',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_pass', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='baggage',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baggages', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='flightstaff',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='flights.flight'),
        ),
        migrations.AddField(
            model_name='flightstaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seat',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flights.aircraft'),
        ),
        migrations.AlterUniqueTogether(
            name='flightstaff',
            unique_together={('user', 'flight', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('aircraft', 'seat_number')},
        ),
    ]
