# Generated by Django 5.2.2 on 2025-06-07 19:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('announcement_type', models.CharField(choices=[('general', 'General'), ('flight_delay', 'Flight Delay'), ('flight_cancellation', 'Flight Cancellation'), ('boarding_call', 'Boarding Call'), ('gate_change', 'Gate Change'), ('security_alert', 'Security Alert'), ('weather_update', 'Weather Update'), ('maintenance', 'Maintenance')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('passengers', 'Passengers'), ('staff', 'Staff'), ('airline_staff', 'Airline Staff'), ('admins', 'Admins'), ('specific_flight', 'Specific Flight')], default='all', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('repeat_announcement', models.BooleanField(default=False)),
                ('repeat_interval', models.PositiveIntegerField(default=0, help_text='Repeat interval in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-read_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('check_in_reminder', 'Check-in Reminder'), ('boarding_call', 'Boarding Call'), ('flight_delay', 'Flight Delay'), ('flight_cancellation', 'Flight Cancellation'), ('gate_change', 'Gate Change'), ('baggage_update', 'Baggage Update'), ('system_alert', 'System Alert')], max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('send_email', models.BooleanField(default=True)),
                ('send_sms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_booking_confirmations', models.BooleanField(default=True)),
                ('email_flight_updates', models.BooleanField(default=True)),
                ('email_check_in_reminders', models.BooleanField(default=True)),
                ('email_promotional', models.BooleanField(default=False)),
                ('sms_booking_confirmations', models.BooleanField(default=False)),
                ('sms_flight_updates', models.BooleanField(default=True)),
                ('sms_check_in_reminders', models.BooleanField(default=False)),
                ('system_announcements', models.BooleanField(default=True)),
                ('system_alerts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
